### ISSUE TITLE
How to apply sum constraint on boolean variables?

### ISSUE THREAD

**Issue by kunalsapru** [chocoteam/choco-solver#554]
### Minimal Working Example

Experienced with choco-solver-_*{4..0.4}*_

```java
    public void minimalWorkingFunc() {
        //Solution map from user
        Map<String, Integer> solution = new TreeMap<String, Integer>();
        solution.put("Feature1", 1);
        solution.put("Feature4", 1);
        
        Model model = new Model();
        Solver solver = model.getSolver();
        int val;
        IntVar v1 = model.boolVar("Feature1");
        IntVar v2 = model.boolVar("Feature2");
        IntVar v3 = model.boolVar("Feature3");
        IntVar v4 = model.boolVar("Feature4");
        IntVar v5 = model.boolVar("Feature5");
        
        List<Constraint> constraints = new ArrayList<Constraint>();
        BoolVar[] boolVars = model.retrieveBoolVars();
        List<BoolVar> newBoolVars = new ArrayList<BoolVar>();
        for(BoolVar bool : boolVars) {
            if(bool.getName().equals("Feature1")) {
                newBoolVars.add(bool);
            }
            if(bool.getName().equals("Feature3")) {
                newBoolVars.add(bool);
            }
            if(bool.getName().equals("Feature4")) {
                newBoolVars.add(bool);
            }
        }
        BoolVar[] allFeaturesInGroup = new BoolVar[newBoolVars.size()];
        allFeaturesInGroup = newBoolVars.toArray(allFeaturesInGroup);

        constraints.add(model.sum(allFeaturesInGroup, "=" , 3));
        
            for(Constraint c : constraints) {
                model.post(c);
                System.out.println("Constraint "+c.toString());
                for(IntVar var : boolVars){
                    if(solution.containsKey(var.getName())){
                        val = solution.get(var.getName());
                        model.getEnvironment().worldPush();
                        try {
                            var.instantiateTo(val, null);
                            solver.propagate();
                        } catch (ContradictionException e) {
                            solver.getEngine().flush();
                            System.out.println("Constraint failed for "+var.getName()+" with value "+val+" --> "+c.toString());
                        }
                        model.getEnvironment().worldPop();
                    }
                }
                model.unpost(c);
            }
    }
```

**Comment by jgFages** [comment]
can you please check with 4.0.5? 
we fixed a bug over boolean sums in 4.0.4

**Comment by kunalsapru** [comment]
Hi,

In the above example, I have a set of boolean variables(features). Now, I want user to select all 3 features Feature1, Feature4 and Feature3. User selects only, Feature1 and Feature4 (in map variable 'solution'). In this case, a constrain fail eror should appear, but I don't see any error.

Also, the scanario may vary, where we want user to only select Feature1 or Feature4 or Feature3
OR and 2 out the 3 features (Feature1, Feature4, Feature3).

Please let me know, if any more explanation is required.

**Comment by kunalsapru** [comment]
Okay. I'll check with 4.0.5.

**Comment by kunalsapru** [comment]
I still get the same behavior with 4.0.5
Output : 

> Constraint SUM ([Feature4 + Feature3 + Feature1 = 3])
> Assigning value 1 to Feature1
> Assigning value 1 to Feature4

Code::
```java

        //Solution map from user
        Map<String, Integer> solution = new TreeMap<String, Integer>();
        solution.put("Feature1", 1);
        solution.put("Feature4", 1);
        
        Model model = new Model();
        Solver solver = model.getSolver();
        int val=100;
        IntVar v1 = model.boolVar("Feature1");
        IntVar v2 = model.boolVar("Feature2");
        IntVar v3 = model.boolVar("Feature3");
        IntVar v4 = model.boolVar("Feature4");
        IntVar v5 = model.boolVar("Feature5");
        
        List<Constraint> constraints = new ArrayList<Constraint>();
        BoolVar[] boolVars = model.retrieveBoolVars();
        List<BoolVar> newBoolVars = new ArrayList<BoolVar>();
        for(BoolVar bool : boolVars) {
            if(bool.getName().equals("Feature1")) {
                newBoolVars.add(bool);
            }
            if(bool.getName().equals("Feature3")) {
                newBoolVars.add(bool);
            }
            if(bool.getName().equals("Feature4")) {
                newBoolVars.add(bool);
            }
        }
        BoolVar[] allFeaturesInGroup = new BoolVar[newBoolVars.size()];
        allFeaturesInGroup = newBoolVars.toArray(allFeaturesInGroup);

        constraints.add(model.sum(allFeaturesInGroup, "=" , 3));
        
            for(Constraint c : constraints) {
                model.post(c);
                System.out.println("Constraint "+c.toString());
                for(IntVar var : boolVars){
                    model.getEnvironment().worldPush();
                    try {
                    	if(solution.containsKey(var.getName())){
                    		val = solution.get(var.getName());
                    		System.out.println("Assigning value "+val+" to "+var.getName());
                            var.instantiateTo(val, null);
                            solver.propagate();
                    	} else {
                    		val = 0;
                			var.instantiateTo(val, null);
                		}
                    } catch (ContradictionException e) {
                        solver.getEngine().flush();
                        System.out.println("Constraint failed for "+var.getName()+" with value "+val+" --> "+c.toString());
                    }
                    model.getEnvironment().worldPop();

                }
                model.unpost(c);
            }
    ```

**Comment by kunalsapru** [comment]
Since, in the above example, Feature1 + Feature4 is 2 because there is no Feature3, the sum is 2, but as per the constraint it should be 3.

**Comment by kunalsapru** [comment]
Hi,
Any ideas would be highly appreciated. 
Many thanks in advance.

**Comment by cprudhom** [comment]
Hi, 
Since you're not using Choco to solve a problem but to check a partial instantiation, the environment is not fully initialized.
Before anything else, the propagation engine and the constraints have to be synchronized.
This is done behind your back when `Solver.solve()` is done but not in your case.
So, before doing anything (that means in your case, before the fpr-loop over constraints) you need to call this line:
```java
 solver.propagate();
```

Then the propagation engine will be set and activated, and anytime a new constraint will be posted, it will be activated automatically.

Hope that helps.

**Comment by cprudhom** [comment]
BTW, it is strongly recommended to give `Cause.Null` as a cause instead of `null` when modifying a variable's domain.

**Comment by cprudhom** [comment]
I forget some calls to propagate.
The working code is:
```java
constraints.add(model.sum(allFeaturesInGroup, "=" , 3));
solver.propagate();
for(Constraint c : constraints) {
    model.post(c);
    System.out.println("Constraint "+c.toString());
    for(IntVar var : boolVars){
        model.getEnvironment().worldPush();
        try {
            solver.propagate();
            if(solution.containsKey(var.getName())){
                val = solution.get(var.getName());
                System.out.println("Assigning value "+val+" to "+var.getName());
                var.instantiateTo(val, Cause.Null);
            } else {
                val = 0;
                var.instantiateTo(val, Cause.Null);
            }
            solver.propagate();
        } catch (ContradictionException e) {
            solver.getEngine().flush();
            System.out.println("Constraint failed for "+var.getName()+" with value "+val+" --> "+c.toString());
        }
        model.getEnvironment().worldPop();

    }
    model.unpost(c);
}
```
The first call to propagate activates the propagation engine, it will be able to receive and activate newly posted constraints.

The second call to propagate is required for the initial propagation because the constraint is posted after having initialized the prop engine. This leads to reduction of the domain of v1, v3 and v4 to `1`, the other ones domain are left unchanged.

The third call to propagate (un-)validates the domain reduction your forced.

Hope this is clearer now.

**Comment by kunalsapru** [comment]
Hi,

Thank you for your reply. If I replace this line
```java
constraints.add(model.sum(allFeaturesInGroup, "=" , 3));
```
with this one
```java
constraints.add(model.sum(allFeaturesInGroup, "=" , 1));
```
The constraint should fail, becuase the expected sum is 1 and actual sum is 2.

**Comment by cprudhom** [comment]
I don't understand, the sum is not equal to 2 except if both variables (v1 and v4) are instantiated together.
But, the code you gave us only check each variable one by one.
If you want to check a complete instantiation, you should do something else.

1. adapt your code to declare the for-loop over variables inside the worldPush/worldPop instructions,
2. with a search strategy (which I recommend) that instantiates all variables in a branch of a search tree;

**Comment by kunalsapru** [comment]
Thanks. It works now. It's always great to have your valuable feedback.
